apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: loki-minio-credentials
  namespace: {{ .Values.schema.namespace }}
spec:
  refreshInterval: 4h0m0s
  secretStoreRef:
    name: external-vault-backend
    kind: ClusterSecretStore
  target:
    name: loki-minio-credentials
    creationPolicy: Owner
    deletionPolicy: "Retain"
  data:
    - secretKey: accessKey
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: "kv/{{ .Values.schema.env }}/loki/minio-credentials-incluster"
        metadataPolicy: None
        property: accessKey
    - secretKey: secretKey
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: "kv/{{ .Values.schema.env }}/loki/minio-credentials-incluster"
        metadataPolicy: None
        property: secretKey
    - secretKey: endpoint
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: "kv/{{ .Values.schema.env }}/loki/minio-credentials-incluster"
        metadataPolicy: None
        property: endpoint
