apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: valkey-users-acl
  namespace: {{ $.Release.Namespace }}
spec:
  refreshInterval: 4h
  secretStoreRef:
    kind: ClusterSecretStore
    name: external-vault-backend
  target:
    name: valkey-users-acl
    creationPolicy: Owner
    deletionPolicy: "Retain"
    template:
      type: Opaque
      data:
        users.acl: |
{{`{{ .auth }}` | indent 10}}
  data:
    - secretKey: auth
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: "kv/{{ .Values.schema.env }}/valkey/acl"
        metadataPolicy: None
        property: auth
