apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: psql-credentials
  namespace: {{ $.Release.Namespace }}
spec:
  refreshInterval: 4h0m0s
  secretStoreRef:
    name: external-vault-backend
    kind: ClusterSecretStore
  target:
    name: psql-credentials
    creationPolicy: Owner
    deletionPolicy: "Retain"
  data:
    - secretKey: user-password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: "kv/{{ .Values.schema.env }}/kestra/psql"
        metadataPolicy: None
        property: user-password
    - secretKey: psql-password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: "kv/{{ .Values.schema.env }}/kestra/psql"
        metadataPolicy: None
        property: psql-password
    - secretKey: repl-password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: "kv/{{ .Values.schema.env }}/kestra/psql"
        metadataPolicy: None
        property: repl-password
