#apiVersion: external-secrets.io/v1
#kind: ExternalSecret
#metadata:
#  name: db-app
#  namespace: {{ $.Release.Namespace }}
#spec:
#  refreshInterval: 4h0m0s
#  secretStoreRef:
#    name: external-vault-backend
#    kind: ClusterSecretStore
#  target:
#    name: db-app
#    creationPolicy: Owner
#    deletionPolicy: "Retain"
#  data:
#    - secretKey: password
#      remoteRef:
#        conversionStrategy: Default
#        decodingStrategy: None
#        key: "kv/{{ $.Values.schema.env }}/n8n/db-app"
#        metadataPolicy: None
#        property: password
