apiVersion: v2
name: argocd
version: 1.0.0
dependencies:
  - name: argo-cd
    repository: https://argoproj.github.io/argo-helm
    version: 9.4.1
  - name: argo-workflows
    version: 0.47.3
    repository: https://argoproj.github.io/argo-helm
#  - name: argo-rollouts
#    version: 2.40.5
#    repository: https://argoproj.github.io/argo-helm
#  - name: argo-events
#    version: 2.4.20
#    repository: https://argoproj.github.io/argo-helm
#  - name: argo-image-updater
#    version: 1.1.0
#    repository: https://argoproj.github.io/argo-helm
#  - name: argo-notifications
#    version: 1.8.1
#    repository: https://argoproj.github.io/argo-helm
#  - name: argo-ci
#    version: 1.0.0
#    repository: https://argoproj.github.io/argo-helm
#  - name: argo-applicationset
#    version: 1.12.1
#    repository: https://argoproj.github.io/argo-helm
#  - name: argo-apps
#    version: 2.0.4
#    repository: https://argoproj.github.io/argo-helm
